export const API_ROUTES = {
    AUTH: {
        OBTAIN_TOKEN: "/login/admin/",
        REFRESH_TOKEN: "/token/refresh/",
        VERIFY_TOKEN: "/token/verify/",
        ME: "/me/",
    },
    STATS: '/stats/',
    BRANCHES: {
        LIST: "/branches/",
        DETAIL: (id: number | string) => `/branches/${id}/`,
        CREATE: "/branches/",
        UPDATE: (id: number | string) => `/branches/${id}/`,
        DELETE: (id: number | string) => `/branches/${id}/`,
    },
    DEPARTMENTS: {
        LIST: "/departments/",
        DETAIL: (id: number | string) => `/departments/${id}/`,
        CREATE: "/departments/",
        UPDATE: (id: number | string) => `/departments/${id}/`,
        DELETE: (id: number | string) => `/departments/${id}/`,
        GET_ALL_EMPLOYEES: (id: number | string) => `/departments/employees/${id}/`,
        GET_ALL_DEPT_EMPLOYEES: (id: number | string) => `/departments/employees/${id}/`,
        GET_ALL_BRANCH_DEPT_EMPLOYEES: (id: number | string) => `/branchdepartments/employees/${id}`,
    },
    EMPLOYEES: {
        LIST: "/employees/",
        DETAIL: (id: number | string) => `/employees/${id}/`,
        CREATE: "/employees/",
        UPDATE: (id: number | string) => `/employees/${id}/`,
        DELETE: (id: number | string) => `/employees/${id}/`,
        UPLOAD_PICTURE: (id: number | string) => `/employees/${id}/profile_picture/upload/`,
        DELETE_PICTURE: (id: number | string) => `/employees/${id}/profile_picture/`,
    },
    MANAGERS: {
        LIST: "/managers/",
        DETAIL: (id: number | string) => `/managers/${id}/`,
        CREATE: "/managers/",
        UPDATE: (id: number | string) => `/managers/${id}/`,
        DELETE: (id: number | string) => `/managers/${id}/`,
    },
    KNOWLEDGE_BASE: {
        FOLDERS: {
            LIST: "/knowledge/folders/",
            DETAIL: (id: number | string) => `/knowledge/folders/${id}/`,
            CREATE: "/knowledge/folders/",
            UPDATE: (id: number | string) => `/knowledge/folders/${id}/`,
            DELETE: (id: number | string) => `/knowledge/folders/${id}/`,
            FOLDER_TREE: "/knowledge/folders/tree/",
        },
        FILES: {
            LIST: "/knowledge/files/",
            DETAIL: (id: number | string) => `/knowledge/files/${id}/`,
            CREATE: "/knowledge/files/",
            UPDATE: (id: number | string) => `/knowledge/files/${id}/`,
            DELETE: (id: number | string) => `/knowledge/files/${id}/`,
            BULK_UPLOAD: "/knowledge/files/bulk-upload/",
        },
        ANNOUNCEMENTS: {
            LIST: "/knowledge/announcements/",
            DETAIL: (id: number | string) => `/knowledge/announcements/${id}/`,
            CREATE: "/knowledge/announcements/",
            UPDATE: (id: number | string) => `/knowledge/announcements/${id}/`,
            DELETE: (id: number | string) => `/knowledge/announcements/${id}/`,
            ATTACHMENTS: {
                LIST: (announcement_id: number | string, employee_id: number | string) => `/knowledge/announcement-attachments?announcement_id=${announcement_id}&employee_id=${employee_id}/`,
                UPLOAD: '/knowledge/announcement-attachments/',
                DELETE_ATTACHMENT: (id: number | string) => `/knowledge/announcement-attachments/${id}/`,
            },
        },
        STATS: "/knowledge/stats/",
        ANNOUNCEMENT_STATS: "/knowledge/announcement-rate/",
    },
    NEW_HIRE: {
        CHECKLISTS: {
            LIST: "/newhire/checklists/",
            DETAIL: (id: number | string) => `/newhire/checklists/${id}/`,
            CREATE: "/newhire/checklists/",
            UPDATE: (id: number | string) => `/newhire/checklists/${id}/`,
            DELETE: (id: number | string) => `/newhire/checklists/${id}/`,
        },
        ATTACHMENTS: {
            LIST: "/newhire/attachments/",
            DETAIL: (id: number | string) => `/newhire/attachments/${id}/`,
            CREATE: "/newhire/attachments/",
            UPDATE: (id: number | string) => `/newhire/attachments/${id}/`,
            DELETE: (id: number | string) => `/newhire/attachments/${id}/`,
        },
        FILES: {
            LIST: "/newhire/attachment-files/",
            DETAIL: (id: number | string) => `/newhire/attachment-files/${id}/`,
            CREATE: "/newhire/attachment-files/",
            DELETE: (id: number | string) => `/newhire/attachment-files/${id}/`,
        },
    },
    EXECUTIVE_MEMBERS: {
        LIST: "/executives/executives/",
        DETAIL: (id: number | string) => `/executives/executives/${id}/`,
        CREATE: "/executives/executives/",
        UPDATE: (id: number | string) => `/executives/executives/${id}/`,
        DELETE: (id: number | string) => `/executives/executives/${id}/`,
        UPLOAD_PICTURE: (id: number | string) => `/executives/executives/${id}/upload-profile-picture/`,
        DELETE_PICTURE: (id: number | string) => `/executives/executives/${id}/delete-profile-picture/`,
    },
    POLLS: {
        LIST: "/knowledge/polls/",
        DETAIL: (id: number | string) => `/knowledge/polls/${id}/`,
        CREATE: "/knowledge/polls/",
        DELETE: (id: number | string) => `/knowledge/polls/${id}/`,
    }
} as const;