/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/executives/executives/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_executives_executives_list"];
        put?: never;
        post: operations["api_executives_executives_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executives/executives/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_executives_executives_retrieve"];
        put: operations["api_executives_executives_update"];
        post?: never;
        delete: operations["api_executives_executives_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_executives_executives_partial_update"];
        trace?: never;
    };
    "/api/executives/executives/{id}/delete-profile-picture/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["api_executives_executives_delete_profile_picture_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executives/executives/{id}/upload-profile-picture/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_executives_executives_upload_profile_picture_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/announcement-attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_announcement_attachments_list"];
        put?: never;
        post: operations["api_knowledge_announcement_attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/announcement-attachments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_announcement_attachments_retrieve"];
        put: operations["api_knowledge_announcement_attachments_update"];
        post?: never;
        delete: operations["api_knowledge_announcement_attachments_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_knowledge_announcement_attachments_partial_update"];
        trace?: never;
    };
    "/api/knowledge/announcements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_announcements_list"];
        put?: never;
        post: operations["api_knowledge_announcements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/announcements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_announcements_retrieve"];
        put: operations["api_knowledge_announcements_update"];
        post?: never;
        delete: operations["api_knowledge_announcements_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_knowledge_announcements_partial_update"];
        trace?: never;
    };
    "/api/knowledge/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_files_list"];
        put?: never;
        post: operations["api_knowledge_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/files/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_files_retrieve"];
        put: operations["api_knowledge_files_update"];
        post?: never;
        delete: operations["api_knowledge_files_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_knowledge_files_partial_update"];
        trace?: never;
    };
    "/api/knowledge/files/bulk-upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_knowledge_files_bulk_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/folders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_folders_list"];
        put?: never;
        post: operations["api_knowledge_folders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/folders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_folders_retrieve"];
        put: operations["api_knowledge_folders_update"];
        post?: never;
        delete: operations["api_knowledge_folders_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_knowledge_folders_partial_update"];
        trace?: never;
    };
    "/api/knowledge/folders/tree/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_knowledge_folders_tree_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newhire/attachment-files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_attachment_files_list"];
        put?: never;
        post: operations["api_newhire_attachment_files_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newhire/attachment-files/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_attachment_files_retrieve"];
        put: operations["api_newhire_attachment_files_update"];
        post?: never;
        delete: operations["api_newhire_attachment_files_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_newhire_attachment_files_partial_update"];
        trace?: never;
    };
    "/api/newhire/attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_attachments_list"];
        put?: never;
        post: operations["api_newhire_attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newhire/attachments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_attachments_retrieve"];
        put: operations["api_newhire_attachments_update"];
        post?: never;
        delete: operations["api_newhire_attachments_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_newhire_attachments_partial_update"];
        trace?: never;
    };
    "/api/newhire/checklists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_checklists_list"];
        put?: never;
        post: operations["api_newhire_checklists_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/newhire/checklists/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_newhire_checklists_retrieve"];
        put: operations["api_newhire_checklists_update"];
        post?: never;
        delete: operations["api_newhire_checklists_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_newhire_checklists_partial_update"];
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials. */
        post: operations["api_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["api_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use. */
        post: operations["api_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Announcement: {
            readonly id: number;
            title: string;
            body: string;
            type?: components["schemas"]["AnnouncementTypeEnum"];
            hash_tags?: unknown;
            is_active?: boolean;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            created_by?: number | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly attachments: {
                [key: string]: unknown;
            }[];
            readonly effective_permissions: {
                [key: string]: unknown;
            };
        };
        AnnouncementAttachment: {
            readonly id: number;
            announcement: number;
            name: string;
            description?: string;
            /** Format: uri */
            file: string;
            readonly file_url: string | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            uploaded_by?: number | null;
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly size: number;
            readonly content_type: string;
            readonly effective_permissions: {
                [key: string]: unknown;
            };
        };
        /**
         * @description * `announcement` - Announcement
         *     * `policy` - Policy
         * @enum {string}
         */
        AnnouncementTypeEnum: "announcement" | "policy";
        Attachment: {
            readonly id: number;
            checklist: number;
            title: string;
            detail?: string | null;
            type?: components["schemas"]["AttachmentTypeEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly files: components["schemas"]["AttachmentFile"][];
        };
        AttachmentFile: {
            readonly id: number;
            attachment: number;
            /** Format: uri */
            file: string;
            /** Format: date-time */
            readonly uploaded_at: string;
        };
        /**
         * @description * `task` - Task
         *     * `training` - Training
         * @enum {string}
         */
        AttachmentTypeEnum: "task" | "training";
        Checklist: {
            readonly id: number;
            title?: string | null;
            detail?: string | null;
            assigned_to: number[];
            assigned_by: number;
            readonly assigned_to_details: components["schemas"]["Employee"][];
            readonly assigned_by_details: components["schemas"]["Employee"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly attachments: components["schemas"]["Attachment"][];
        };
        Employee: {
            readonly id: number;
            emp_name: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            role?: string | null;
            education?: string | null;
            bio?: string | null;
            /** Format: uri */
            profile_picture?: string | null;
            branch_department: number;
        };
        Executive: {
            readonly id: number;
            name: string;
            address: string;
            city: string;
            phone: string;
            /** Format: email */
            email: string;
            role: string;
            education: string;
            bio?: string;
            /** Format: uri */
            profile_picture?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        KnowledgeFile: {
            readonly id: number;
            folder: number;
            name: string;
            description?: string;
            /** Format: uri */
            file: string;
            readonly file_url: string | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            uploaded_by?: number | null;
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly size: number;
            readonly content_type: string;
            readonly effective_permissions: {
                [key: string]: unknown;
            };
        };
        KnowledgeFolder: {
            readonly id: number;
            name: string;
            description?: string;
            parent?: number | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            created_by?: number | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly effective_permissions: {
                [key: string]: unknown;
            };
        };
        PaginatedAnnouncementAttachmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AnnouncementAttachment"][];
        };
        PaginatedAnnouncementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Announcement"][];
        };
        PaginatedAttachmentFileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AttachmentFile"][];
        };
        PaginatedAttachmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Attachment"][];
        };
        PaginatedChecklistList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Checklist"][];
        };
        PaginatedExecutiveList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Executive"][];
        };
        PaginatedKnowledgeFileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["KnowledgeFile"][];
        };
        PaginatedKnowledgeFolderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["KnowledgeFolder"][];
        };
        PatchedAnnouncement: {
            readonly id?: number;
            title?: string;
            body?: string;
            type?: components["schemas"]["AnnouncementTypeEnum"];
            hash_tags?: unknown;
            is_active?: boolean;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            created_by?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly attachments?: {
                [key: string]: unknown;
            }[];
            readonly effective_permissions?: {
                [key: string]: unknown;
            };
        };
        PatchedAnnouncementAttachment: {
            readonly id?: number;
            announcement?: number;
            name?: string;
            description?: string;
            /** Format: uri */
            file?: string;
            readonly file_url?: string | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            uploaded_by?: number | null;
            /** Format: date-time */
            readonly uploaded_at?: string;
            readonly size?: number;
            readonly content_type?: string;
            readonly effective_permissions?: {
                [key: string]: unknown;
            };
        };
        PatchedAttachment: {
            readonly id?: number;
            checklist?: number;
            title?: string;
            detail?: string | null;
            type?: components["schemas"]["AttachmentTypeEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            readonly files?: components["schemas"]["AttachmentFile"][];
        };
        PatchedAttachmentFile: {
            readonly id?: number;
            attachment?: number;
            /** Format: uri */
            file?: string;
            /** Format: date-time */
            readonly uploaded_at?: string;
        };
        PatchedChecklist: {
            readonly id?: number;
            title?: string | null;
            detail?: string | null;
            assigned_to?: number[];
            assigned_by?: number;
            readonly assigned_to_details?: components["schemas"]["Employee"][];
            readonly assigned_by_details?: components["schemas"]["Employee"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly attachments?: components["schemas"]["Attachment"][];
        };
        PatchedExecutive: {
            readonly id?: number;
            name?: string;
            address?: string;
            city?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            role?: string;
            education?: string;
            bio?: string;
            /** Format: uri */
            profile_picture?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedKnowledgeFile: {
            readonly id?: number;
            folder?: number;
            name?: string;
            description?: string;
            /** Format: uri */
            file?: string;
            readonly file_url?: string | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            uploaded_by?: number | null;
            /** Format: date-time */
            readonly uploaded_at?: string;
            readonly size?: number;
            readonly content_type?: string;
            readonly effective_permissions?: {
                [key: string]: unknown;
            };
        };
        PatchedKnowledgeFolder: {
            readonly id?: number;
            name?: string;
            description?: string;
            parent?: number | null;
            inherits_parent_permissions?: boolean;
            permitted_branches?: number[];
            permitted_departments?: number[];
            permitted_employees?: number[];
            created_by?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly effective_permissions?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description * `draft` - Draft
         *     * `publish` - Publish
         * @enum {string}
         */
        StatusEnum: "draft" | "publish";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_executives_executives_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExecutiveList"];
                };
            };
        };
    };
    api_executives_executives_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Executive"];
                "application/x-www-form-urlencoded": components["schemas"]["Executive"];
                "multipart/form-data": components["schemas"]["Executive"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executive"];
                };
            };
        };
    };
    api_executives_executives_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executive"];
                };
            };
        };
    };
    api_executives_executives_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Executive"];
                "application/x-www-form-urlencoded": components["schemas"]["Executive"];
                "multipart/form-data": components["schemas"]["Executive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executive"];
                };
            };
        };
    };
    api_executives_executives_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_executives_executives_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExecutive"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExecutive"];
                "multipart/form-data": components["schemas"]["PatchedExecutive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executive"];
                };
            };
        };
    };
    api_executives_executives_delete_profile_picture_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_executives_executives_upload_profile_picture_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this executive. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Executive"];
                "application/x-www-form-urlencoded": components["schemas"]["Executive"];
                "multipart/form-data": components["schemas"]["Executive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executive"];
                };
            };
        };
    };
    api_knowledge_announcement_attachments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnnouncementAttachmentList"];
                };
            };
        };
    };
    api_knowledge_announcement_attachments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AnnouncementAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["AnnouncementAttachment"];
                "application/json": components["schemas"]["AnnouncementAttachment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementAttachment"];
                };
            };
        };
    };
    api_knowledge_announcement_attachments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementAttachment"];
                };
            };
        };
    };
    api_knowledge_announcement_attachments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AnnouncementAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["AnnouncementAttachment"];
                "application/json": components["schemas"]["AnnouncementAttachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementAttachment"];
                };
            };
        };
    };
    api_knowledge_announcement_attachments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_knowledge_announcement_attachments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedAnnouncementAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAnnouncementAttachment"];
                "application/json": components["schemas"]["PatchedAnnouncementAttachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementAttachment"];
                };
            };
        };
    };
    api_knowledge_announcements_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnnouncementList"];
                };
            };
        };
    };
    api_knowledge_announcements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Announcement"];
                "application/x-www-form-urlencoded": components["schemas"]["Announcement"];
                "multipart/form-data": components["schemas"]["Announcement"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
        };
    };
    api_knowledge_announcements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
        };
    };
    api_knowledge_announcements_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Announcement"];
                "application/x-www-form-urlencoded": components["schemas"]["Announcement"];
                "multipart/form-data": components["schemas"]["Announcement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
        };
    };
    api_knowledge_announcements_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_knowledge_announcements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this announcement. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAnnouncement"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAnnouncement"];
                "multipart/form-data": components["schemas"]["PatchedAnnouncement"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
        };
    };
    api_knowledge_files_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedKnowledgeFileList"];
                };
            };
        };
    };
    api_knowledge_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["KnowledgeFile"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeFile"];
                "application/json": components["schemas"]["KnowledgeFile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFile"];
                };
            };
        };
    };
    api_knowledge_files_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFile"];
                };
            };
        };
    };
    api_knowledge_files_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["KnowledgeFile"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeFile"];
                "application/json": components["schemas"]["KnowledgeFile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFile"];
                };
            };
        };
    };
    api_knowledge_files_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_knowledge_files_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedKnowledgeFile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedKnowledgeFile"];
                "application/json": components["schemas"]["PatchedKnowledgeFile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFile"];
                };
            };
        };
    };
    api_knowledge_files_bulk_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["KnowledgeFile"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeFile"];
                "application/json": components["schemas"]["KnowledgeFile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFile"];
                };
            };
        };
    };
    api_knowledge_folders_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedKnowledgeFolderList"];
                };
            };
        };
    };
    api_knowledge_folders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeFolder"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeFolder"];
                "multipart/form-data": components["schemas"]["KnowledgeFolder"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFolder"];
                };
            };
        };
    };
    api_knowledge_folders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge folder. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFolder"];
                };
            };
        };
    };
    api_knowledge_folders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge folder. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeFolder"];
                "application/x-www-form-urlencoded": components["schemas"]["KnowledgeFolder"];
                "multipart/form-data": components["schemas"]["KnowledgeFolder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFolder"];
                };
            };
        };
    };
    api_knowledge_folders_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge folder. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_knowledge_folders_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this knowledge folder. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedKnowledgeFolder"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedKnowledgeFolder"];
                "multipart/form-data": components["schemas"]["PatchedKnowledgeFolder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFolder"];
                };
            };
        };
    };
    api_knowledge_folders_tree_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFolder"];
                };
            };
        };
    };
    api_newhire_attachment_files_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttachmentFileList"];
                };
            };
        };
    };
    api_newhire_attachment_files_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentFile"];
                "application/x-www-form-urlencoded": components["schemas"]["AttachmentFile"];
                "multipart/form-data": components["schemas"]["AttachmentFile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentFile"];
                };
            };
        };
    };
    api_newhire_attachment_files_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentFile"];
                };
            };
        };
    };
    api_newhire_attachment_files_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentFile"];
                "application/x-www-form-urlencoded": components["schemas"]["AttachmentFile"];
                "multipart/form-data": components["schemas"]["AttachmentFile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentFile"];
                };
            };
        };
    };
    api_newhire_attachment_files_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_newhire_attachment_files_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment file. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttachmentFile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachmentFile"];
                "multipart/form-data": components["schemas"]["PatchedAttachmentFile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentFile"];
                };
            };
        };
    };
    api_newhire_attachments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttachmentList"];
                };
            };
        };
    };
    api_newhire_attachments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
                "multipart/form-data": components["schemas"]["Attachment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    api_newhire_attachments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    api_newhire_attachments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
                "multipart/form-data": components["schemas"]["Attachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    api_newhire_attachments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_newhire_attachments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this attachment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachment"];
                "multipart/form-data": components["schemas"]["PatchedAttachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    api_newhire_checklists_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChecklistList"];
                };
            };
        };
    };
    api_newhire_checklists_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Checklist"];
                "application/x-www-form-urlencoded": components["schemas"]["Checklist"];
                "multipart/form-data": components["schemas"]["Checklist"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
        };
    };
    api_newhire_checklists_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this checklist. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
        };
    };
    api_newhire_checklists_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this checklist. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Checklist"];
                "application/x-www-form-urlencoded": components["schemas"]["Checklist"];
                "multipart/form-data": components["schemas"]["Checklist"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
        };
    };
    api_newhire_checklists_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this checklist. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_newhire_checklists_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this checklist. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChecklist"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChecklist"];
                "multipart/form-data": components["schemas"]["PatchedChecklist"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checklist"];
                };
            };
        };
    };
    api_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    api_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
}
